### ISSUE TITLE
Choose which '.env' file should be used

### ISSUE THREAD

**Issue by AmadeusK525** [levibostian/dotenv-ios#13]
As of now, the script is hardcoded to parse the `.env` file, so the user isn't allowed to specify which version of the file they'll like to use (`.env.release`, `.env.development`...). The user should be able to specify if they'd like and, if not specified at all, it should fall back to `.env`

**Comment by levibostian** [comment]
Works for me! Thank you so very much for your contribution! 

I have never needed that option before. I use [this CLI tool](https://github.com/levibostian/cici) to prepare my environment before deployment with only 1 `.env` active at a time. You use the tool to delete the current `.env` file and replace it with different values. 

I have not touched this project in a while. I recently refactored the [android dotenv project](https://github.com/levibostian/dotenv-android) from a ruby CLI tool to a build script. I have considered doing the same to this project to make it easier to integration into an XCode project and use. So, you might want to consider eventually adding this feature to [this CLI](https://github.com/levibostian/dotenv) which the android and future ios tools will use at it's core.

**Comment by AmadeusK525** [comment]
Hi @levibostian, thank you for merging the PR 🙂 

I'll make sure to take a look at the tool you mentioned, it seems very interesting. The reason why I chose to add the option to choose the desired `.env` file is that it'll marry well with the [fastlane best practices](https://docs.fastlane.tools/best-practices/keys/#dotenv) that are documented in their official website.

I have taken a quick look at the [base CLI](https://github.com/levibostian/dotenv) tool that both the iOS and Android projects use, so, when needed, I'll see about doing the same contribution to it. And last of all, thank you for the great tools you've made!
